import Head from 'next/head'
import Navbar from '../components/navbar'
import Hero from '../components/hero'
import About from '../components/about'
import Content from '../components/contents'
import Footer from '../components/footer'
import Premium from '../components/premium'

export default function Home() {
  return (
    <div>
      <Head>
        <title>ATOM</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Hero />
      <About />
      <Content />
      <Premium />
      <Footer />
    </div>
  )
}
